import {createContext,useContext,useState,ReactNode,useEffect} from 'react';
import {X,CheckCircle2,AlertCircle,Search,ArrowUpRight} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Incident} from '../types';
import {label,date,remaining,terminal} from '../utils/format';
const ToastContext=createContext<(message:string,error?:boolean)=>void>(()=>{});
export function ToastProvider({children}:{children:ReactNode}){const [items,setItems]=useState<{id:number;message:string;error:boolean}[]>([]);function toast(message:string,error=false){const id=Date.now()+Math.random();setItems(v=>[...v,{id,message,error}]);setTimeout(()=>setItems(v=>v.filter(t=>t.id!==id)),error?12000:4500);}return <ToastContext.Provider value={toast}>{children}<div className="toasts" role="status">{items.map(t=><div className={'toast '+(t.error?'error':'')} key={t.id}>{t.error?<AlertCircle size={20}/>:<CheckCircle2 size={20}/>}<span>{t.message}</span><button aria-label="Dismiss notification" onClick={()=>setItems(v=>v.filter(x=>x.id!==t.id))}><X size={16}/></button></div>)}</div></ToastContext.Provider>;}
export const useToast=()=>useContext(ToastContext);
export function Badge({value}:{value:string}){return <span className={'badge '+value.toLowerCase()}><i/>{label(value)}</span>;}
export function PageHeader({eyebrow='FACTORY OPERATIONS',title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="header-actions">{children}</div></div>;}
export function Loading(){return <div aria-label="Loading" className="skeletons">{[1,2,3].map(i=><div className="skeleton" key={i}/>)}</div>;}
export function Empty({text='No records match your selection.'}:{text?:string}){return <div className="empty"><Search size={28}/><h3>Nothing here yet</h3><p>{text}</p></div>;}
export function ErrorState({error,retry}:{error:any;retry?:()=>void}){return <div className="empty error"><AlertCircle/><h3>Couldn’t load this view</h3><p>{error?.response?.data?.detail||error?.message||'Please try again.'}</p>{retry&&<button onClick={retry}>Retry</button>}</div>;}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[onClose]);return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></header>{children}</section></div>;}
export function SLA({due,status}:{due:string;status:string}){const [,tick]=useState(0);useEffect(()=>{const id=setInterval(()=>tick(x=>x+1),30000);return()=>clearInterval(id);},[]);return <span className={!terminal(status)&&new Date(due).getTime()<Date.now()?'overdue':'muted'}>{terminal(status)?'Completed':remaining(due)}</span>;}
export function IncidentTable({rows}:{rows:Incident[]}){return rows.length?<div className="table-wrap"><table><thead><tr><th>Incident / report</th><th>Equipment</th><th>Severity</th><th>Status</th><th>Assigned to</th><th>SLA</th><th/></tr></thead><tbody>{rows.map(i=><tr key={i.id}><td><Link className="record-link" to={'/incidents/'+i.id}>{i.incident_number}</Link><div className="truncate muted">{i.description}</div></td><td><strong>{i.machine_code}</strong><div className="muted small">{i.machine_name}</div></td><td><Badge value={i.severity}/></td><td><Badge value={i.status}/></td><td>{i.assigned_user}<div className="muted small">{i.department}</div></td><td><SLA due={i.sla_due_at} status={i.status}/></td><td><Link aria-label={'Open '+i.incident_number} to={'/incidents/'+i.id}><ArrowUpRight size={17}/></Link></td></tr>)}</tbody></table></div>:<Empty/>;}
export function RawTable({rows,columns}:{rows:any[];columns:string[]}){return rows.length?<div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{label(c)}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id??index} id={'record-'+row.id}>{columns.map(c=><td key={c}>{typeof row[c]==='object'?JSON.stringify(row[c]):c.endsWith('_at')||c==='timestamp'?date(row[c]):String(row[c]??'—')}</td>)}</tr>)}</tbody></table></div>:<Empty/>;}
