import {Link,useParams} from 'react-router-dom';
import {useState} from 'react';
import {Factory,Thermometer,Activity,ArrowUpRight,Download,ArrowLeft} from 'lucide-react';
import {useLookup,useData} from '../hooks/data';
import {useSession} from '../stores/session';
import {PageHeader,Loading,ErrorState,Badge,IncidentTable,RawTable,Empty,useToast} from '../components/ui';
import {download,errorMessage} from '../services/api';
import {terminal} from '../utils/format';
export function Machines({map=false}:{map?:boolean}){const {data:lookup,isLoading,error}=useLookup();const {factory,user}=useSession();const [search,setSearch]=useState('');if(isLoading)return <Loading/>;if(error)return <ErrorState error={error}/>;const lines=lookup!['production-lines'].filter(l=>String(l.factory_id)===factory);const stations=lookup!.stations.filter(s=>lines.some(l=>l.id===s.production_line_id));const machines=lookup!.machines.filter(m=>stations.some(s=>s.id===m.station_id)&&(m.machine_name+' '+m.machine_code).toLowerCase().includes(search.toLowerCase()));const card=(m:any)=><Link to={'/machines/'+m.id} className="machine-card" key={m.id}><div><span className="machine-icon"><Factory/></span><Badge value={m.status}/></div><span className="eyebrow">{m.machine_code}</span><h2>{m.machine_name}</h2><p>{lookup?.stations.find(s=>s.id===m.station_id)?.name} · {m.model}</p><div className="machine-thresholds"><span><Thermometer size={15}/>Warn {m.warning_temperature}°C</span><span><Activity size={15}/>Warn {m.warning_vibration} mm/s</span></div><div className="machine-card-footer">View equipment record<ArrowUpRight size={17}/></div></Link>;return <><PageHeader title={map?'Factory map':'Machine workspace'} description={map?'Navigate your factory, line by line and station by station.':'Equipment health, operating parameters, and maintenance history.'}>{user?.role==='Admin'&&<Link className="button primary" to="/settings?section=machines">Configure machines</Link>}</PageHeader><div className="filters"><input placeholder="Find equipment…" aria-label="Find equipment" value={search} onChange={e=>setSearch(e.target.value)}/></div>{map?lines.map(l=><section className="factory-line" key={l.id}><h2><Factory size={20}/>{l.name}<span>{l.code}</span></h2>{stations.filter(s=>s.production_line_id===l.id).map(s=><div className="station-group" key={s.id}><h3>{s.name}<small>{s.code}</small></h3><div className="machine-grid">{machines.filter(m=>m.station_id===s.id).map(card)}</div></div>)}</section>):<div className="machine-grid">{machines.map(card)}</div>}{!machines.length&&<Empty/>}</>;}
export function MachineDetail(){const {id}=useParams(),{data,isLoading,error}=useData('/machines/'+id);const toast=useToast();const {data:lookup}=useLookup();if(isLoading)return <Loading/>;if(error)return <ErrorState error={error}/>;return <><Link className="back-link" to="/machines"><ArrowLeft size={15}/>Equipment</Link><PageHeader eyebrow={data.machine_code} title={data.machine_name} description={`${data.manufacturer} · ${data.model} · Serial ${data.serial_number}`}><Badge value={data.status}/></PageHeader><div className="three-columns"><section className="panel"><h2>Equipment location</h2><dl><div><dt>Station</dt><dd>{lookup?.stations.find(s=>s.id===data.station_id)?.name}</dd></div><div><dt>Critical equipment</dt><dd>{data.is_critical?'Yes':'No'}</dd></div><div><dt>Open tickets</dt><dd>{data.incidents.filter((i:any)=>!terminal(i.status)).length}</dd></div></dl></section><section className="panel"><h2>Temperature thresholds</h2><div className="parameter"><Thermometer/><strong>{data.warning_temperature}°C<small>Warning</small></strong><strong>{data.critical_temperature}°C<small>Critical</small></strong></div></section><section className="panel"><h2>Vibration thresholds</h2><div className="parameter"><Activity/><strong>{data.warning_vibration}<small>Warning · mm/s</small></strong><strong>{data.critical_vibration}<small>Critical · mm/s</small></strong></div></section></div><section className="panel"><div className="panel-title"><h2>Recent incidents &amp; maintenance history</h2><Link to={'/query?machine_id='+id}>Query this machine <ArrowUpRight size={16}/></Link></div><IncidentTable rows={data.incidents}/></section><section className="panel"><h2>Recent machine logs</h2><RawTable rows={data.logs} columns={['id','timestamp','temperature','vibration','pressure','runtime','production_count','stock_level','status_code']}/></section><section className="panel"><div className="panel-title"><h2>Maintenance documents &amp; manuals</h2><Link to={'/documents?machine_id='+id}>Manage documents</Link></div>{data.documents.length?data.documents.map((d:any)=><div className="document-row" key={d.id}><div><strong>{d.title}</strong><p>{d.document_type} · Revision {d.revision} · {d.tags}</p></div><button onClick={()=>download('/files/documents/'+d.id,d.filename).catch(e=>toast(errorMessage(e),true))}><Download size={16}/>Download</button></div>):<Empty text="Upload a manual or maintenance guide to this machine."/>}</section></>;}
